In [2]:
import requests

In [4]:
import pandas as pd

In [5]:
import numpy as np

In [6]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [7]:
a=np.array([1,2,3,4])

In [19]:
b=np.array([0,.5,1,1.5,2])

In [25]:
b[[0,2,-1]]

array([0., 1., 2.])

In [ ]:
Indexing and slicing of matrices

In [26]:
# Square matric
A= np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [27]:
A[1]

array([4, 5, 6])

In [28]:
A[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [29]:
A[1][2]

6

In [30]:
A[0][2]

3

In [31]:
A[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [32]:
A[:2,:2]

array([[1, 2],
       [4, 5]])

In [33]:
A[:2,2:]

array([[3],
       [6]])

In [34]:
#Assisgning new values to a row in an array
A[1]=np.array([10,10,10])

In [35]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])